name: Deploy static content to Pages

on:
  push:
    branches: ["build"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v2

      - name: Rename auth.html to index.html
        run: |
          mv templates/auth.html templates/index.html
          ls templates

      - name: Upload static files
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'templates'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        id: deployment
